server:
  port: 20001

spring:
  application:
    name: Jbone-sys-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: root
    password: opc@2018
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jbone_sys?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
  sleuth:
    sampler:
      probability: 1
    messaging:
      enabled: true
      rabbit:
        enabled: true
  zipkin:
    sender:
      type: rabbit
zipkin.rabbitmq.queue: zipkin


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}


management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude:
      base-path: /actuator
  endpoint:
    health:
      show-details: ALWAYS

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 200000
        semaphore:
          maxConcurrentRequests: 200
  threadpool:
    default:
      coreSize: 100


jbone:

  sys:
    serverName: jbone-sys-server



info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
  java:
    version: ${java.version}
  code:
    git: https://github.com/417511458/jbone
    gitee: https://gitee.com/majunwei2017/jbone
  domain: http://www.jbone.cn


