spring:
  application:
    name: jbone-sm-admin
  redis:
    host: 127.0.0.1
    port: 6379
    password: jbone
  cloud:
    config:
    enabled: false
  boot:
    admin:
      monitor:
        connect-timeout: 30000
        default-retries: 2
      turbine:
        location: http://jbone-sm-monitor.majunwei.com:10003/
      context-path: /admin

server.port: 10002

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}


management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude:
      base-path: /actuator
  endpoint:
    health:
      show-details: ALWAYS


jbone:
  cas:
    casServerUrl: http://localhost:30001/cas
    currentServerUrlPrefix: http://localhost:10002
    casFilterUrlPattern: /cas
    successUrl: /admin/
    logoutUrl: /admin/logout
    unauthorizedUrl: /403
    clientSessionTimeout: 1800000

    filterChainDefinition:
      "[/actuator/**]": anon
      "[/admin/**]": authc,roles[serverAdministrator]
      "[/**]": anon

  sys:
    serverName: jbone-sm-admin
    serverProtoal: http://
  rpc.sysServer.feign:
    protocol: http
    name: jbone-sys-server


info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
  java:
    version: ${java.version}
  code:
    git: https://github.com/417511458/jbone
    gitee: https://gitee.com/majunwei2017/jbone
  domain: http://www.jbone.cn

hystrix.command.default.execution.timeout.enabled: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
hystrix.command.default.execution.isolation.strategy: THREAD
hystrix.threadpool.default.coreSize: 100
hystrix.command.default.execution.isolation.thread.interruptOnTimeout: true
hystrix.command.default.execution.isolation.thread.interruptOnCancel: false
