server:
  port: 10001

spring:
  application:
    name: Jbone-sm-register


management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude:
      base-path: /actuator
  endpoint:
    health:
      show-details: ALWAYS


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.251.35.116:10001/eureka,http://10.163.185.74:10001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}


info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
  java:
    version: ${java.version}
  code:
    git: https://github.com/417511458/jbone
    gitee: https://gitee.com/majunwei2017/jbone
  domain: http://www.jbone.cn
